### ISSUE TITLE
Make word substituions as such: (I don't think this is a great solution)

### ISSUE THREAD

**Issue by jack-davidson** [jack-davidson/cb1#1]
```json
{
    "my name is": "hello,"
}
```
such that "my name is" -> "hello"

**Comment by jack-davidson** [comment]
But I also think that extracting tokens from a sentence is the best idea because if the sentence is not recognized our bot will have no context.

**Comment by rachitkakkar** [comment]
What would the tokens be?

**Comment by jack-davidson** [comment]
words in english just as tokens in a programming language are syntax elements of that

**Comment by jack-davidson** [comment]
ooh okay I found a module that would be very helpful in that regard, python nltk, natural language toolkit

**Comment by rachitkakkar** [comment]
Ok, let me check it out

**Comment by rachitkakkar** [comment]
I see no difference from identifying a name as a string of tokens (Ex. ["My", "name", "is", "NAME: JOHN DOE"]) and just using a regex to match the "My name is" part.

**Comment by rachitkakkar** [comment]
Regex also allows us to do other complex stuff like find the parts before "is sad", and our bot could do something like add I'm sorry to the beginning of the sentence. The it becomes "I'm sorry {thing} is sad"

**Comment by jack-davidson** [comment]
I think the conventional way to go about this is to have a table of query:response and then using the jaccard similarity index to find the closest match to query or response.

**Comment by rachitkakkar** [comment]
Yeah, that would be better than regex.

**Comment by rachitkakkar** [comment]
Because if strings don't match perfectly, our bot won't know how to respond

**Comment by jack-davidson** [comment]
just gonna put this here:
![image](https://user-images.githubusercontent.com/73897725/112002158-9b297600-8aed-11eb-89bc-d3cd82f98a9a.png)

**Comment by jack-davidson** [comment]
it will help with jaccard similarity index because it uses set theory symbols

**Comment by jack-davidson** [comment]
![image](https://user-images.githubusercontent.com/73897725/112002253-b0060980-8aed-11eb-9456-0ae90fd97500.png)

**Comment by jack-davidson** [comment]
![image](https://user-images.githubusercontent.com/73897725/112002294-bac09e80-8aed-11eb-8211-6f00c05aea1a.png)

**Comment by jack-davidson** [comment]
![image](https://images.deepai.org/glossary-terms/jaccard-index-9707615.jpg)

**Comment by jack-davidson** [comment]
this basically means the jaccard index of set A and set B is the cardinality of a intersect between A and B over the cardinality of a union between A and B

**Comment by jack-davidson** [comment]
btw cardinality means length of a set

**Comment by jack-davidson** [comment]
![image](https://miro.medium.com/max/2400/1*XiLRKr_Bo-VdgqVI-SvSQg.png)

**Comment by rachitkakkar** [comment]
Is the sets of A and B made up of characters, words, or whatever we want.

**Comment by rachitkakkar** [comment]
And do you have the repl.it link?

**Comment by jack-davidson** [comment]
yes I submitted it

**Comment by rachitkakkar** [comment]
We both need to submit it

**Comment by jack-davidson** [comment]
we will just pull in the changes every time

**Comment by jack-davidson** [comment]
https://replit.com/join/fhgpggwi-jackdavidson1

**Comment by rachitkakkar** [comment]
thanks

**Comment by jack-davidson** [comment]
yes the sets are made of meaningful words and not stop words

**Comment by jack-davidson** [comment]
the at which as etc

**Comment by jack-davidson** [comment]
but the jaccard index just takes the cardinality of that, so that is how they can be divided

**Comment by rachitkakkar** [comment]
I ran `git pull` bc the repl was out of sync with the commit I made to chatbot.py'

**Comment by jack-davidson** [comment]
:+1:

**Comment by rachitkakkar** [comment]
Ok so the way I understand it is that if we have set A = {'my', 'name', 'is'} and B = ['name', 'is'] the index would be {'name', 'is'}/{'my'}

**Comment by rachitkakkar** [comment]
I found the following code that allows us to calculate this:
```python
import numpy as np

a = [0, 1, 2, 5, 6, 8, 9]
b = [0, 2, 3, 4, 5, 7, 9]

#define Jaccard Similarity function
def jaccard(list1, list2):
    intersection = len(list(set(list1).intersection(list2)))
    union = (len(list1) + len(list2)) - intersection
    return float(intersection) / union

#find Jaccard Similarity between the two sets 
jaccard(a, b)

0.4
```

But this will add numpy as a dependency, which means we should create a requirements.txt.

**Comment by rachitkakkar** [comment]
This article as reference:
https://www.statology.org/jaccard-similarity-python/

**Comment by rachitkakkar** [comment]
PS RK Coding is my second account

**Comment by jack-davidson** [comment]
looks good

**Comment by jack-davidson** [comment]
Did you receive my contact email?
