### ISSUE TITLE
The respond to function actually doesn't work

### ISSUE THREAD

**Issue by rachitkakkar** [jack-davidson/cb1#6]
I'll tell details next class.

**Comment by jack-davidson** [comment]
please tell details

**Comment by jack-davidson** [comment]
I see you have changed the respond function so that might be it

**Comment by rachitkakkar** [comment]
I only added logging

**Comment by rachitkakkar** [comment]
The function works with keywords for the first response, but the second response and third response doesn't work

**Comment by rachitkakkar** [comment]
so
'i dropped my phone in water damage' -> 'you may have water damage'
'i cracked my screen' -> *doesn't know*
'my battery only lasts 5 minutes' -> *doesn't know*

**Comment by jack-davidson** [comment]
I know how to fix this I think

**Comment by jack-davidson** [comment]
I will just rewrite the function again next class

**Comment by jack-davidson** [comment]
also the algorithm is designed for sentences so I would just put "I dropped my phone in water" as a sentence and it will match most versions of that

**Comment by jack-davidson** [comment]
buy maybe lets start our dataset with just general speech and then we can continue with customer service as customer service is harder to do, lets start simple

**Comment by rachitkakkar** [comment]
no customer service is easier because we only have to expect conversations about phones, and we can just use keywords to identify the responses. general conversation can lead anywhere

**Comment by rachitkakkar** [comment]
because if you say
'i spilled liquid on my phone' -> *it will say water damage*
so we can program a bunch of responses just using keywords

**Comment by rachitkakkar** [comment]
and it actually works for water damage

**Comment by rachitkakkar** [comment]
just the fields after the first don't work

**Comment by jack-davidson** [comment]
okay that makes sense though maybe we should structure them more like
sentences otherwise we could just do `if keyword in ...`. The most accurate
sentence will match like "I dropped my phone in a puddle" will match with "
I dropped my phone in water"

**Comment by rachitkakkar** [comment]
Yeah, the current system works fine but why is it not responding to the other data in the json? (Not just the first element)

**Comment by jack-davidson** [comment]
maybe just compatibility issue. I think if I rewrite the chatbot it will
work
